### ISSUE TITLE
Support Dark Mode

### ISSUE THREAD

**Issue by jgw96** [pwa-builder/pwa-install#1]
## Goal
The component should detect when the browser is in dark mode and update the UI to match.

## Things to keep in mind
 - We should make sure our dark mode is accessible https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni
- Colors should be [declared as css variables](https://github.com/pwa-builder/pwa-install/blob/master/src/pwa-install.ts#L21) so they are customize-able

**Comment by kenchris** [comment]
@tomayac :D

**Comment by jgw96** [comment]
Removing this from the 1.0 milestone for now as its something i want to tackle after 1.0 (this is just an enhancement at this point anyways).
