### ISSUE TITLE
Close X doesn't listen to --modal-z-index (css-variable)

### ISSUE THREAD

**Issue by VanheeArne** [pwa-builder/pwa-install#10]
When changing the z-index via the css variable to e.g.: 1 , the close X is behind the modal

https://glitch.com/~woozy-edam

**Comment by jgw96** [comment]
Thanks for opening an issue with us! I just fixed this with https://github.com/pwa-builder/pwa-install/commit/cfb83bfc28362b6f10b9cf50acd48b3e3dca120b and it will be in the next release.
