### ISSUE TITLE
Page still scrollable while modal is up

### ISSUE THREAD

**Issue by hipstersmoothie** [pwa-builder/pwa-install#103]
**Describe the bug**

When the modal is active the page below it is still scrollable.

**To Reproduce**
1. Use web component
2. click install
3. attempt to scroll modal, sometimes page scrolls

**Expected behavior**

The main page should not be scrollable.

**Comment by jgw96** [comment]
Merged the PR you opened that fixed this, thanks a ton @hipstersmoothie !
