### ISSUE TITLE
Improve focus styling

### ISSUE THREAD

**Issue by hipstersmoothie** [pwa-builder/pwa-install#104]
**Describe the bug**

When I open the install modal the cursor focus stays in the same place on the page and I cannot 

**To Reproduce**
1. Use web component
2. Open it
3. Focus remains on trigger element

**Expected behavior**

When the install modal is up the focus should get moved to somewhere within the modal. Once focus is moved into the modal focus should be locked into the modal. This will prevent the user from tabbing to content outside the modal.

EDIT: The focus might be moving but since there are no focus styles it is quite hard to tell.

**Comment by jgw96** [comment]
@hipstersmoothie do you feel like there is more to be done here with focus work?

**Comment by hipstersmoothie** [comment]
The last thing that's needed is a focus-lock when the modal is up. It can lead to weird behavior if no lock is present. 

1. Run example
2. Click the 2nd install button
3. `Shift + Tab`
4. `Enter`
5. 2 modals up at the same time ❌

**Comment by jgw96** [comment]
Awesome, ok cool

**Comment by lee-leonardo** [comment]
this is an accessibility concern as well. I'll make the modifications required alongside the laundry list of other smaller things
