### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by nicksterFL** [pwa-builder/pwa-install#11]
I receive Uncaught TypeError: Failed to resolve module specifier "lit-element". Relative references must start with either "/", "./", or "../". on the www/index.html

also when I click "install" i receive:
(index):39 Uncaught TypeError: document.querySelector(...).openPrompt is not a function
    at HTMLButtonElement.<anonymous> ((index):39)

what am I missing?

**Comment by jgw96** [comment]
Hey! How are you using the element? It sounds like you may be trying to run the repo but without doing `npm install` first?

**Comment by nicksterFL** [comment]
yeah that's what it was. I'm good now.

**Comment by jgw96** [comment]
All good, thanks for giving the component a try!
