### ISSUE TITLE
Support localization

### ISSUE THREAD

**Issue by J0ne** [pwa-builder/pwa-install#13]
Would be nice if the headers ("key features", "description" ) could be overridden. 

Thank you very much for your good work!

**Comment by jgw96** [comment]
No problem at all, this is definitely something that is on our roadmap! If you don't mind me asking, what would you think would be the best way to do this? Would you prefer to be able to edit them through properties? (something like `<pwa-install featuresheader="text" />`

**Comment by J0ne** [comment]
Thanks for asking! That is actually something I'd think would work great. For instance, we (at work project) have to support 2 - 3 languages. We use polyglot.js and it would look something like
`<pwa-install .featuresheader=${polyglot.t(this.lang + '.featureHeader')} />`
Of course, the content in manifest.json should include all languages ("Lorem ipsum / Some text ").
- Unless it was possible override manifest.json blocks also...

**Comment by jgw96** [comment]
Perfect, this is really good info. As far as the manifest goes, i'm not sure its in the scope of this component to handle that, but we should definitely handle letting developers pass their own headers. Would you like to work on this issue? (you can check out our contributing guide here https://github.com/pwa-builder/pwa-install/blob/master/CONTRIBUTING.md and i'm more than willing to help if needed). Otherwise, I can add this feature myself.

**Comment by J0ne** [comment]
At the moment I'm really busy with my work project (it should be production-ready in a couple of weeks) and I've never done any coding with typescript (and I'm not so pro with GitHub either). 

But anyway, it would be nice to try to contribute and give something back. I'll take a look at the guide and try to find some time. Please, prepare to answer some stupid questions :)

**Comment by J0ne** [comment]
My very first pull request is here https://github.com/pwa-builder/pwa-install/pull/16
I just couldn't add any reviewers. :-/ I wasn't sure ho tow do this pr properly so I forked the repo, made changes and then did pr comparing those forks (that's why there is reverse and reverse of reverse...).

**Comment by jgw96** [comment]
Hey @J0ne , huge thanks for the PR, you did it exactly correct! Its totally fine that you had to fix some git issues, I still struggle with git all the time. Congrats on your first ever pull request and welcome to the PWABuilder community!

**Comment by J0ne** [comment]
Great! Thank you very much. I'm glad I did something useful. Not much but it's a start. :)
