### ISSUE TITLE
Can't see third screenshot on desktop

### ISSUE THREAD

**Issue by HowardWolosky** [pwa-builder/pwa-install#137]
**Describe the bug**
This is a regression that occurred in the 1.2.7 release (it didn't occur in prior releases).
On desktop, if you have three screenshots, you're unable to click to the right on the second screenshot in order to see the third.  On mobile (where drag gestures work), you can still see the third.

**To Reproduce**
1. Have a manifest with three screenshots.
2. Use `<script type="module" src="https://cdn.jsdelivr.net/npm/@pwabuilder/pwainstall@1.2.6"></script>` with `<pwa-install />`
3. Note that you can get to all three screenshots.
4. Now use `<script type="module" src="https://cdn.jsdelivr.net/npm/@pwabuilder/pwainstall@1.2.6"></script>` with `<pwa-install />`
5. Note that you can't get past the second screenshot.

**Expected behavior**
Always be able to see all screenshots.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.18362.592
 - Browser: Edge Dev
 - Version: 81.0.389.2

**Comment by jgw96** [comment]
Thanks Howard!
