### ISSUE TITLE
[Feature] showeligible attribute

### ISSUE THREAD

**Issue by benjibuiltit** [pwa-builder/pwa-install#14]
I would prefer that if I were ineligible for installing a PWA (on a supported browser), the install button is simply not shown. It would save me the click/confusion to see a modal with only a cancel button.

I'd like to propose adding a showeligible attribute to the component, that only shows the install button when a user is eligible on supported browsers.

This issue has spawned from #7

**Comment by jgw96** [comment]
Awesome, thanks @benjibuiltit ! Let me know if you need any help getting started (:

**Comment by jgw96** [comment]
Released in 0.9.9 , thanks!
