### ISSUE TITLE
[Feature Request] Add a method to check if the pwa is already installed

### ISSUE THREAD

**Issue by rdhainaut** [pwa-builder/pwa-install#161]
**Describe the feature**
I use a custom button as trigger for the pwa install dialog.
It works great.  But now i would like be able to check if the pwa is already installed to display or not this custom button.

In code 

```
   <pwa-install
      usecustom
      manifestpath="/manifest.webmanifest"
    >
    </pwa-install>

    <button
      type="button"
      @click="OpenInstall()"
    >
      Install custom
    </button>
```
```
  public OpenInstall(): void {
    const pwaInstallButton = document.querySelector("pwa-install");
    if (pwaInstallButton) {
      (pwaInstallButton as any).openPrompt();
    }
  }
```

It s not really important but the sample code above is used in vue.js project (class based) + typescript

**Comment by FluorescentHallucinogen** [comment]
I'll create a pull request for that. :wink:

**Comment by richardtaylordawson** [comment]
This would be an awesome feature! It may even be nice to just add an attribute to the pwa-install component of a data-target that links to the custom button so that it hides the custom button for you if you don't have showopen set to true. A method is good as well. :)

**Comment by jgw96** [comment]
Hello all! So it sounds like the main issue here is that the button is still showing once the PWA has been installed? If that did not happen, would it cover this feature request?

**Comment by richardtaylordawson** [comment]
Yes that would complete this issue in my mind as long as if they continue to revisit the site later that the button is hid if it’s installed as well.

**Comment by jgw96** [comment]
Thanks for the feedback, ill look into implementing this then.

**Comment by jgw96** [comment]
Hello all! I have fixed this bug (i'm calling it a bug that the button was showing after the app had been installed) and added a method to check if the PWA is installed in the above linked PR. I have requested a review from my teammates so once it has been reviewed they will merge it and I will do a release. Thanks everyone!

**Comment by richardtaylordawson** [comment]
@jgw96 Awesome! I'm so excited for this!

**Comment by richardtaylordawson** [comment]
@jgw96 I went to implement this tonight on my site and here is what I found.

1. If you use the out of the box button, everything works perfect! The only problem is it's hard to customize the look because the only variable is for the button color so it doesn't quite match the rest of the site buttons.
2. If you use a custom button, on page load when using `document.querySelector("pwa-install"). getInstalledStatus()` it keeps saying it's undefined. I'm not super familiar with web components but I'm assuming that maybe the component isn't on the page quite yet on page load and so I can't check install status yet? Does that seem correct? Any tips in implementing would be awesome :D

**Comment by rdhainaut** [comment]
@richardtaylordawson I don t know if it can help but this is my code to hide a custom pwa install button 

```js
    const pwaInstallButton = document.getElementById("pwaInstallButton");
    if (pwaInstallButton) {
      pwaInstallButton.style.display = "none";

      window.addEventListener("beforeinstallprompt", (event) => {
        pwaInstallButton.style.display = "block";
      });

      window.addEventListener("appinstalled", (event) => {
        pwaInstallButton.style.display = "none";
      });
    }
```
