### ISSUE TITLE
[Idea] Show rating and reviews from Microsoft Store

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [pwa-builder/pwa-install#162]
Does Microsoft Store have an API?

If yes, it would be really nice to fetch and display rating (stars) and reviews (comments) for PWAs published in Microsoft Store.

If no, what about creating this API?

**Comment by jgw96** [comment]
Hey @FluorescentHallucinogen , sorry about the delay here! This is outside the scope of this component currently and does not line up with our future plans. Because of this I am going to close this issue for now, but please always feel free to open an issue with us or share ideas!
