### ISSUE TITLE
Screenshot Carousel - Safari Desktop & Mobile

### ISSUE THREAD

**Issue by richardtaylordawson** [pwa-builder/pwa-install#177]
**Describe the bug**
The screenshot carousel in the modal doesn't work on Safari desktop & mobile.

**Expected behavior**
I believe that when pressing a left or right arrow that it should move to the next screenshot 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Smartphone (please complete the following information):**
 - OS: iOS
 - Browser Safari

**Comment by lee-leonardo** [comment]
should be fixed, lost permissions so I can't close this issue
