### ISSUE TITLE
Call to action is below the fold on iOS 

### ISSUE THREAD

**Issue by tomayac** [pwa-builder/pwa-install#208]
Unfortunately the call to action (“Tap the share button and then 'Add to Homescreen'”) is below the fold on iOS.

It seems like in an SFSafariViewController the container is at least scrollable (but its options  don’t include “Add to Homescreen”), but in stand-alone Safari it’s not even scrollable, so impossible to discover. 

![CCE3DE9C-9BDF-4723-88A8-F9BE8B55D203](https://user-images.githubusercontent.com/145676/76899239-6f026600-6897-11ea-8c4a-4ba9ddfa7b2a.png)

My suggestion would be to absolutely superimpose the call to action at the bottom, and make the description then fade away under it and make it scrollable.

**Comment by jgw96** [comment]
Hey @tomayac ! This was improved in the latest release (v1.4.2), but I am working on another release today to polish the iOS experience. Ill ping here when that release is out, thanks!

**Comment by jgw96** [comment]
Fixed with https://github.com/pwa-builder/pwa-install/commit/0d544d48dc4f3191e41931eced5af8eba1f55ac2 , thanks again @tomayac !

**Comment by tomayac** [comment]
Thanks for fixing this!
