### ISSUE TITLE
[Question] styling with CSS variables

### ISSUE THREAD

**Issue by Sacrekin** [pwa-builder/pwa-install#245]
I can style PWA Install with the parts but not with the CSS variables. Safari does not support parts. Tried it in  the glitch demo and it does not work. Can you provide an example how to make it work?

**Comment by jgw96** [comment]
Hey @Sacrekin , let me take a look and ill get back to you, thanks for opening an issue with us!

**Comment by jgw96** [comment]
Hey @Sacrekin , this ended up being a bug in my code! I just released a fix, if you install v1.6.2 (or you can just use the script tag like in the glitch demo) the css variable for the background button color will now work, thanks!

**Comment by Sacrekin** [comment]
Thanks. I will have a look at it.

By the way, I also noticed that the modal behaviour (incl close button) isn’t working in desktop mode.

Also, using the glitch demo app, try to run it on an iPhone (IOS 12.4 in my case). The Tap… message is in full transparency, the background isn’t blurred as intended.


Just FYI. Do you want me to post 2 issues?

Kind regards,



Jean-Marie Sacré
jm@sacre.us
GSM: +33.68281.3011
Skype: sacrekin
