### ISSUE TITLE
CSS selector not working

### ISSUE THREAD

**Issue by chansiawwei** [pwa-builder/pwa-install#247]
**Question in detail**

I wanted to make the images in the carousel larger but i am having issue on selecting the img tag. I am aware that the provided css variable does not include it, any advice is much appreciated ! 

**Is your question related to a problem? Please describe.**

I am having issue with css selector in the pwa install modal.

**Describe alternatives you've considered**
Using my own custom css to style the component

**Additional context**

**Comment by jgw96** [comment]
Hey @chansiawwei thanks for opening a issue with us, which img tag are you wanting to style?

**Comment by chansiawwei** [comment]
Hi @jgw96 , i am referring to the img tag within the carousel

**Comment by jgw96** [comment]
@chansiawwei thanks for the reply, Ill add a CSS part to enable the images to be styled. The reason you are not able to style it currently is because we are using [shadow dom](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) in our components.

**Comment by jgw96** [comment]
Just an update here: I am going to close this as a not fix for now. After working on the carousel with one of my teammates who was also using it, we decided to not make the images in the carousel styleable as it is too easy to then break the entire layout of the carousel. Thanks for the suggestions @chansiawwei !
