### ISSUE TITLE
Localization: install button text as a property

### ISSUE THREAD

**Issue by J0ne** [pwa-builder/pwa-install#25]
The install button text should also be a property so that it could be localised as well. 
This is related to https://github.com/pwa-builder/pwa-install/issues/13 but I realised that afterwards

**Comment by jgw96** [comment]
Hey @J0ne good idea! Were you intending to add this? If not we will add it, just asking to make sure were not duplicating work (:

**Comment by J0ne** [comment]
I could do that tomorrow. (I'm located in Finland, it's now 09 PM, so it means something like... in next 20 hours :D)  Would that be ok? 
Btw, last time I forked the repo and made changes to that one. Is it a good way to do PR or is it ok to do straight to the original repo?

**Comment by jgw96** [comment]
Hey @J0ne , thats the best way to do a PR. Thank you again!

**Comment by J0ne** [comment]
Awesome! Thank you.
