### ISSUE TITLE
Error 404 pwa-install.js.map

### ISSUE THREAD

**Issue by nadfri** [pwa-builder/pwa-install#293]
Hi,
Can you fix the error 404 which appears in the console?

DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/@pwabuilder/pwa-install.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by aggressivecarwraps** [comment]
Hi, I'm getting this error now. It's 404-ing again.
