### ISSUE TITLE
new method: closePrompt()	

### ISSUE THREAD

**Issue by vincentmorneau** [pwa-builder/pwa-install#31]
This library is really really good.

We have `openPrompt()`. Can we get `closePrompt()` ?

**Comment by jgw96** [comment]
Added with https://github.com/pwa-builder/pwa-install/commit/d6ffbaf6432dba7d270394a77289fafc6c41eeb5 . Thanks @vincentmorneau !

**Comment by vincentmorneau** [comment]
awesome, thank YOU!
