### ISSUE TITLE
Layout on iPhone 5SE

### ISSUE THREAD

**Issue by vincentmorneau** [pwa-builder/pwa-install#33]
**Describe the bug**
This can be tested on https://pwainstall.glitch.me/ with an iPhone 5SE

**Screenshots**
![image](https://user-images.githubusercontent.com/5391291/69020925-2b98f900-0984-11ea-973b-427db65ded70.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 5SE
 - OS: iOS 13
 - Browser Safari
 - Version Latest

**Additional context**
Also, it's difficult to scroll vertically through the modal (get to the bottom) when my thumb starts from the carousel component because of the horizontal scrolling within the carousel.

**Comment by dfabulich** [comment]
A similar problem occurs on iPhone 11 Pro Max

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-11-18 at 11 03 41](https://user-images.githubusercontent.com/96150/69081630-40f93c00-09f3-11ea-81e2-6307643390b0.png)

**Comment by jgw96** [comment]
Hey @dfabulich , could you give this another try here https://pwainstall.glitch.me and see if it looks better better for you now?

**Comment by dfabulich** [comment]
It's always hard to figure out whether I've properly updated my service worker, but I see no change at all on either my iPhone 11 Pro Max or iPhone 8 simulator.

**Comment by jgw96** [comment]
Ahh interesting, ill take a second look at this

**Comment by jgw96** [comment]
Added another fix along with this commit https://github.com/pwa-builder/pwa-install/commit/0662516c3153400a3355e5065b5c8aacbe76afa7 and confirmed with testing. Thanks @dfabulich ! If you ever spot any more safari / iOS issues always feel free to open an issue.
