### ISSUE TITLE
Should hide after install

### ISSUE THREAD

**Issue by jgw96** [pwa-builder/pwa-install#34]

**Comment by benjibuiltit** [comment]
How do you see this differing from the showeligible attribute? Is it a matter of scope and adding a check to see if the app is being launched as standalone from iOS?

**Comment by jgw96** [comment]
Thanks for asking (: This is more around making sure that after an app has been installed to the homescreen (or desktop) that the button internal to the component will be hidden even when the showeligible attribute isn't being used. I've seen people using this in demos with the default button and realized that even when someone isn't using the showeligible attribute we should hide the button once an app has been installed. It's bad UX in my opinion for the button to still be there.

**Comment by benjibuiltit** [comment]
I agree. I figured there was a nuance there I was missing. Thanks for clarifying!

**Comment by jgw96** [comment]
All good 😊
