### ISSUE TITLE
Install button not showing on Firefox

### ISSUE THREAD

**Issue by dagalumin** [pwa-builder/pwa-install#342]
Hello, thank you for your work, but despite of many tries I've done, the "Install" button doesn't show in Firefox (desktop and mobile), while it correctly displays on on other browsers. 
This happens for my project but also just for your demo page https://pwainstall.glitch.me/ . I've tested in different desktop and mobile environments. I guess something is wrong since your pwa-install component is described as compatible with firefox?
The PWA works fine.

Tested versions are Firefox 77.0.1 (64 bit) on Windows 10 desktops,
and Firefox app v. 68.9.0 on Android smartphone (Huawei P30 Pro)

Thank you so much

**Comment by jgw96** [comment]
Hello, thanks for opening an issue with us and sorry for the delay. I actually just responded to this exact situation here https://github.com/pwa-builder/pwa-install/issues/345 so I am going to close this issue with the same message. Thanks for using PWABuilder!
