### ISSUE TITLE
Install button doesnt appear on other browsers except chrome

### ISSUE THREAD

**Issue by oladele-david** [pwa-builder/pwa-install#345]
**Install button doesnt appear on other browsers except chrome**
After adding the script  tags as documented in the appropriate place, i discovered  that the button doesnt appear on other broswers like Opera, Firefox, Tor, Phoenix, Safari (I haven't tested it yet on safari but guess it might be the same issue) browsers.
 i think  it might be because  its not yet compactable with other browsers Yet. But it will be nice if you could look into it, or if there is way to go around it.
Thanks.

**Comment by MrPeker** [comment]
I have same problem

**Comment by jgw96** [comment]
Hello all! This component is currently only supported in Chromium based browsers and Safari. The beforeInstallPrompt event has only ever been implemented by Chromium based browsers such as Chrome, Edge, Samsung Internet, Opera and more. Firefox has unfortunately never consistenly implemented this event and has not had a consistently available install experience for PWAs either. However, we are heavily involved in the spec process for installing PWAs, so we hope to make progress on this. Thanks everyone!
