### ISSUE TITLE
show/hide events

### ISSUE THREAD

**Issue by vincentmorneau** [pwa-builder/pwa-install#36]
This would be very useful

```js
document.querySelector("pwa-install").addEventListener("show", function(){
   // do something...
});

document.querySelector("pwa-install").addEventListener("hide", function(){
   // do something...
});
```

**Comment by jgw96** [comment]
Agreed! I was thinking about this same thing the other night, i definitely think this would be worth adding. Would you be interested in doing a pull request? All good if not of course, but I can help if needed and we have a contributing guide here https://github.com/pwa-builder/pwa-install/blob/master/CONTRIBUTING.md . Just let me know and then Ill move forward on this (:

**Comment by vincentmorneau** [comment]
Unfortunately not. I stubbled across your project for my app https://fab.earth, a PWA to fight climate change. Too much invested there already, but I'm looking forward to publish my next release with pwa-install

**Comment by jgw96** [comment]
That's awesome, all good! I have added this to the 1.0 milestone and will update this issue once I have implemented this.

**Comment by jgw96** [comment]
Added with https://github.com/pwa-builder/pwa-install/commit/8135536b78f74c7850ef57491e3f73dd9298a66b . Thanks @vincentmorneau (:
