### ISSUE TITLE
Override Component CSS without Shadow Parts

### ISSUE THREAD

**Issue by rizwan-ishtiaq** [pwa-builder/pwa-install#406]
**Question in detail**
Shadow Parts is a good way to control design. But In old broswers it will not work. For example safari 10. Can you suggest some mehtod from which i can change design in old browsers with can example?

**Describe alternatives you've considered**
In documentation i can see `usecustom`  i assume i can implement a button and interactions myself. But how can you provide any example?

Thanks for creating this awesome component.

**Comment by lee-leonardo** [comment]
@rizwan-ishtiaq 
You should be able to use css variables and modify them with the parent element's css, using the :host selector.
Here's the google developer's tutorial.
https://developers.google.com/web/fundamentals/web-components/shadowdom#host

I checked mdn and it looks like it should work on Safari 10.

https://developer.mozilla.org/en-US/docs/Web/CSS/:host()
https://developer.mozilla.org/en-US/docs/Web/CSS/--*

**Comment by jgw96** [comment]
Hello all! As css variables are now widely supported and CSS shadow parts are rapidly gaining support I am going to be closing this for now. Thanks!
