### ISSUE TITLE
Multiple entries from the manifest file are not being processed

### ISSUE THREAD

**Issue by bobvmierlo** [pwa-builder/pwa-install#418]
**Describe the bug**
Multiple entries from the manifest.json file are not being processed by the pwa install script.

**To Reproduce**
I placed the following entries in the manifest.json file, however the only one that actually does something in the modal is the 'description'. All the rest don't change anything in the install modal.

```json
    "explainer": "Uitleg hier!",
    "description": "Test beschrijving van de app.",
    "installbuttontext": "App installeren.",
    "iosinstallinfotext": "Druk op de 'Share' knop en vervolgens op 'Zet op beginscherm' om de app op je homescreen te zetten"
```

**Expected behavior**
I would expect those entries to change the text in the modal, nothing works though.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro (20H2)
 - Browser: Chrome
 - Version: 85.0.4183.83

**Comment by lee-leonardo** [comment]
@bobvmierlo the text such as 
`installbuttontext` and `iosinstallinfotext` are attributes on the element, not entries in the manifest.
