### ISSUE TITLE
PWABuilder build App not obey the Screen Orientation as per the Manifest defined

### ISSUE THREAD

**Issue by sunBhabani** [pwa-builder/pwa-install#433]
Hi Support,

As I have already defined (**"orientation": "portrait"**) in my manifest for restrict my APP only view as a portrait mode. Not to view in Landscape mode. And it's also works fine and obey the orientation rule i.e Portrait-mode when I installed/run by ServiceWorker prompt.

But after building the APP on PWABuilder and then lunched by play-store, my APP don't obey the manifest defined orientation. It works both on Landscape & Portrait mode. Which I don't want to do. I think some fix need to solve this. Would you please help me to achieve this.

**Comment by jgw96** [comment]
Closing this as it is not relevant to the repo.
