### ISSUE TITLE
[Question] npmignore 

### ISSUE THREAD

**Issue by Mister-Hope** [pwa-builder/pwa-install#453]
Why is the package bundling all the files? 🙄

It does make sense to bundle ts files for ts users to import them. That's OK.

But why uploading the whole repo even including `.github` folder?

This will encrease the package size, and affects a package size display if that package is depending this package.

**Comment by lee-leonardo** [comment]
@Mister-Hope are you using tree shaking? That could help with the bundle size on your end. I'm assuming that's the main reason why the package itself was upoading everything. I'll look to making the change on our end, it's a good point, not necessary to include the repo as is.

**Comment by Mister-Hope** [comment]
> @Mister-Hope are you using tree shaking? That could help with the bundle size on your end. I'm assuming that's the main reason why the package itself was upoading everything. I'll look to making the change on our end, it's a good point, not necessary to include the repo as is.

I wany to use this package in my package, but now npm will calculate more size then it should be. That's what i mean.😅

**Comment by lee-leonardo** [comment]
I understand, but with webpack or rollup tree shaking, in your end bundle it should only include the code, not anything else. That would be the expected behavior. npm will download everything onto your machine, but that's usually misleading and hence usually developers usually use bundle analysis tools.

https://www.npmjs.com/package/webpack-bundle-analyzer

**Comment by jgw96** [comment]
Hello all! We are just using the standard bundling method with Rollup. While NPM does tell you that your downloading alot of code, it does this for every package and has always been misleading. As @lee-leonardo , I would recommend using a bundle analyzer of some sort. You can also use Edge devtools network tab https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/ to get a good idea of what code is being loaded. For example, here is the pwa-install component 
![image](https://user-images.githubusercontent.com/8823093/97470063-531e7280-1904-11eb-99dc-b9e37e473aa6.png) and as you can see its only loading the code it needs (and is only a touch over 11 kb (: ). Thanks for opening an issue with us!

**Comment by Mister-Hope** [comment]
Hey, bro ! What I see is from the npm docs, Is that it only encourage to upload the files which will be used when your module is required by another application, instead of uploading unrelated files.  It doesn't matter how you bundled or created the final output file.  And it also doesn't matter how the structure of the repo is.  But only the files which one will be used when your model is being required, Or other files which could be required in some situations should be up loaded. That's what I wanna express.

 And also npm do encourage you to upload a readme.md together with the package file.  Again, I don't think feels like those files (e.g. `.github` `test`)  should be uploaded.
