### ISSUE TITLE
[Question] LICENSE

### ISSUE THREAD

**Issue by Mister-Hope** [pwa-builder/pwa-install#454]
Can the repo use a standard format of MIT LICENSE file?

Github can not recognize it.

**Comment by lee-leonardo** [comment]
The license follows the ISC format, which removes some of the unnecessary clauses in the MIT license. I understand the MIT label is within the license itself, but they are fundamentally the same. Is this an issue within Github or npm? From what I can tell it looks fine in npm.

**Comment by Mister-Hope** [comment]
Github is showing that it has a "other“ type of license. 
 You can just follow the license format of webpack eslint and other famous repoes license.
![Screenshot_20201028-115528](https://user-images.githubusercontent.com/33315834/97389072-81a44980-1914-11eb-85b1-ee9c370e0557.jpg)
![Screenshot_20201028-115518](https://user-images.githubusercontent.com/33315834/97389077-849f3a00-1914-11eb-878e-51cce4240b8a.jpg)
![Screenshot_20201028-115457](https://user-images.githubusercontent.com/33315834/97389083-87019400-1914-11eb-8c1b-822c33084cbe.jpg)

 I think it's that the githubs issue,  It needs the copyrights to place before the license content and after the MIT license title.

**Comment by jgw96** [comment]
Hello all! This is in fact a Github issue, we are using the license we are required to use. Thanks!
