### ISSUE TITLE
[Question] Lack of docs

### ISSUE THREAD

**Issue by Mister-Hope** [pwa-builder/pwa-install#455]
The readme is a bit simple.

As you can see, it's had for people to debug it because it's difficult to serve a service worker on dev server.

While the readme is lack of description about property usage.

E.g.: How should I use the `showopen` property? What is the logic of displaying "install button" now? Will the button still appears even the PWA is installed after I set it to true? Or the button  keep showing unless user install it? If I don't set it, when should the button be displayed?

If users have to spend time reading from source code to understand it, or they have to waste time finding it through debuging, why don't they write some codes of their own?

**Comment by Mister-Hope** [comment]
The most rediculous thing is:

https://github.com/pwa-builder/pwa-install/blob/d5fabc828864df8a2712c485793bfa1a18b1798b/src/pwa-install.ts#L19

showOpen only appear once here

**Comment by lee-leonardo** [comment]
Thanks for bringing this up, I've taken a look, and it has no usages. I am assuming it was intended to be used, but then the spec changed and this attribute is not being used. I'm going to remove it alongside the other updates mentioned in other issues.

We do have guides on medium to help developers use the component.
https://medium.com/pwabuilder/installing-progressive-web-apps-b7274ebffe80

**Comment by jgw96** [comment]
@Mister-Hope lets also remember please that its actual people working behind the scenes on these projects. Because of that, calling something "rediculous" seems to be a little out of place. Let's please keep things professional (:
