### ISSUE TITLE
Change install button text

### ISSUE THREAD

**Issue by mfwebmaster** [pwa-builder/pwa-install#557]
Good day all

Not sure if this is the correct forum but I would like to know how to change the text within the install b button.

I understand two elements involved in the process
<pwa-install></pwa-install>
installbuttontext 

I cannot figure out how to change this.

**Comment by erfan226** [comment]
Hi. You can use the markup below, I hope it does what you need to achieve:
<pwa-install explainer="some description" installbuttontext="Install this app now!" featuresheader="some textual detail..." descriptionheader="more explanations" cancelbuttontext="Cancel installation" pwa-install="Install..."></pwa-install>
