### ISSUE TITLE
Bad experience when beforeinstallprompt hasn't fired yet

### ISSUE THREAD

**Issue by dfabulich** [pwa-builder/pwa-install#6]
To repro: Visit https://pwainstall.glitch.me/ in desktop Chrome Incognito mode. This is your first time visiting the site, in incognito mode, so pwainstall.glitch.me is not eligible to request installation. Click the Install button.

Actual: The install screen pops up, but in place of an "Install" button, there's just a "Close" button, with no visible call to action.

Expected: An Install button; when you click it, it should give the user browser-specific directions on how to manually install the PWA, like this https://github.com/cubiq/add-to-homescreen

**Comment by jgw96** [comment]
Hey @dfabulich , because this experience is being designed as part of the Safari guided install experience I am going to link this issue to #7 and close this one

**Comment by jgw96** [comment]
I also edited that issue to reflect this
