### ISSUE TITLE
Images don't display on Safari

### ISSUE THREAD

**Issue by dfabulich** [pwa-builder/pwa-install#8]
Open https://pwainstall.glitch.me in iOS Safari 13.2.2 (but the version doesn't much matter) and click the Install button.

The images are missing on the install screen.

![IMG_16E275A83DAA-1](https://user-images.githubusercontent.com/96150/68441909-7183df00-0184-11ea-83ea-b29c76f2406f.jpeg)

**Comment by dfabulich** [comment]
This also affects desktop Safari 13.0.3 for macOS.

![image](https://user-images.githubusercontent.com/96150/68441970-924c3480-0184-11ea-9804-b1381e1ea8c4.png)

**Comment by jgw96** [comment]
@dfabulich do you mind if we combine this with your other Safari issue? I'm wanting to use that issue as a tracker for the Safari specific experience

**Comment by dfabulich** [comment]
I think that this issue #8 has essentially nothing to do with issue #7 ("Doesn't work on Safari"). This issue is due to WebP images being sent to Safari. (Safari doesn't support WebP.)

**Comment by dfabulich** [comment]
FYI, my user agent is:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36

**Comment by jgw96** [comment]
Ahh got ya, thanks for the info. So the webp images would be coming from your manifest, this component does nothing special with the images from your manifest. Can you confirm that?

**Comment by jgw96** [comment]
Sorry about the confusion here @dfabulich , i now know the cdn i was using for images on the demo serves webp files to Safari even though Safari is the only browser left that does not support webp. I changed to just using the glitch cdn which serves png's, so were good now. Thanks again!
