### ISSUE TITLE
Issue on non 3:2 13 inch displays

### ISSUE THREAD

**Issue by vincentmorneau** [pwa-builder/pwa-install#80]
I would reopen #32 

Still getting this on macbook pro 13'' display:

![image](https://user-images.githubusercontent.com/5391291/70654314-0e261a80-1c24-11ea-9edd-6f3c2c3c3223.png)

**Comment by jgw96** [comment]
Thanks for the heads up!

**Comment by jgw96** [comment]
Thanks to @hipstersmoothie this has been fixed, thanks everyone!
