### ISSUE TITLE
User Agent sniffing fails to take into account iPadOS

### ISSUE THREAD

**Issue by hober** [pwa-builder/pwa-install#86]
[pwa-install.ts line 506](https://github.com/pwa-builder/pwa-install/blob/463a8af46027bee16c518de8ca2eab1b3368bd20/src/pwa-install.ts#L506) attempts to detect iOS by User Agent sniffing:

```js
    this.isIOS = navigator.userAgent.includes('iPhone') || navigator.userAgent.includes('iPad');
```

But iPads running iPadOS report a User Agent string similar to desktop Safari's, and this test fails on them.

**Comment by jgw96** [comment]
Good catch! Ill make sure this gets fixed up. @hober by chance could you copy and paste the full user agent for an iPad running iPad OS please?
