### ISSUE TITLE
Misplaced close X

### ISSUE THREAD

**Issue by dfabulich** [pwa-builder/pwa-install#9]
In Chrome 78.0.3904.87, go to https://pwainstall.glitch.me/ and click Install.

Actual: The close X appears outside the dialog box

![image](https://user-images.githubusercontent.com/96150/68442114-e35c2880-0184-11ea-8d96-c8685563be77.png)

Expected: The close X should be inside the dialog box

**Comment by jgw96** [comment]
@dfabulich would you mind giving this https://pwainstall.glitch.me/ a try again and see if you still run into this issue?

**Comment by dfabulich** [comment]
Not fixed. Tested in a fresh incognito window.

**Comment by dfabulich** [comment]
FYI, my user agent is:

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.87 Safari/537.36

**Comment by jgw96** [comment]
hmmm, i'm having trouble reproducing this. What size is the viewport when this happens? Can you repro here https://webboard-app.web.app/ too?

**Comment by dfabulich** [comment]
Yes, I repro there as well. The issue occurs when the viewport is greater than 1200px. If I resize under that, the dialog fills the full screen; above that, it greys out the background.

**Comment by jgw96** [comment]
Thanks, I was finally able to reproduce this! I just fixed this with https://github.com/pwa-builder/pwa-install/commit/cfb83bfc28362b6f10b9cf50acd48b3e3dca120b and https://github.com/pwa-builder/pwa-install/commit/24274d7634f701a89a3bcc59522be648ce7e54f6. These fixes will be in the next release
